### ISSUE TITLE
Integrate with D3

### ISSUE THREAD

**Issue by ssured** [oeo4b/kriging.js#3]
Hi

A couple of weeks ago I mentioned your code to Mike Bostock, author of D3, see https://github.com/mbostock/d3/issues/1617

It would be awesome to integrate your kriging implementation into D3. Are you interested in creating a plugin?

Cheers,
 Sjoerd

**Comment by maciekfreak** [comment]
@ssured Do you have still your work on this project from http://weett.nl/kriging/index.html ? This link doesn't work anymore.I'm trying to do similar thing and also use kriging.js on Leaflet. I think that project can help me a lot.

Thanks

**Comment by ssured** [comment]
Here you are sir https://gist.github.com/ssured/532463fb6a810637213a

Have fun and please share your progress!

**Comment by caiquevallim** [comment]
@ssured hey man ! I need it, I learned how I can use this algorithm, but I need that return some array with coordinates, bcuz I need use it with heat map, can you help me ?

**Comment by ssured** [comment]
Sorry man, I have no current knowledge anymore on this code. Wish you good luck!

**Comment by caiquevallim** [comment]
hey man ! I need it, I learned how I can use this algorithm, but I need that return some array with coordinates, bcuz I need use it with heat map, can you help me ?

@oeo4b

**Comment by santiblanko** [comment]
@oeo4b maybe you can use turf.js

**Comment by logantpowell** [comment]
Sorry to poke in on a closed issue here. I'm at the Census Bureau and we're starting a new OSS project wherein this could make a real impact for Census users... Might @oeo4b and @ssured be willing to chat about a potential collaboration?

**Comment by ssured** [comment]
@logantpowell feel free to reach out to me at sjoerd @ weett dot nl . Please note I'm Dutch living in the Netherlands, don't know if that's an issue. Kind regards!

**Comment by gagan-bansal** [comment]
@logantpowell I am also interesting in such project. Though I was not involved in the development of this project but I have used the lib in our project [Delhi air quality](http://www.rediff.com/news/report/rediff-labs-real-time-air-quality-monitoring-for-delhi/20160201.htm) for interpolation.

If you are discussing your requirement on some open forum or github issue I can be part of that and can understand the scope of work.
