### ISSUE TITLE
Array.prototype.rep is unnecessary and causing errors

### ISSUE THREAD

**Issue by aleksandervines** [oeo4b/kriging.js#5]
The function Array.prototype.rep is essentially just creating an array of size n with a specific value. It is only ~~used~~ creating issues in kriging_matrix_diag, which creates an array of size n^2 with the value 0. It is also a recursive function and will create a massive amount of recursive calls. When n is around ~350, javascript (at least in my version of chrome) will respond with a nice "javascript Uncaught RangeError: Maximum call stack size exceeded" error.

I solved this by replacing Z = [ 0 ].rep(n \* n) in kriging_matrix_diag with:

```
    var Z = [];
    var len = n * n;
    for ( var i = 0; i < len; i++) {
        Z.push(0);
    }
```

Of course, ~~if this is needed elsewhere,~~ it is quite easy to extract this as a method of len and value and apply to other places where rep is called :) This method is much faster than the rep one, so that should be done.

**Comment by oeo4b** [comment]
@aleksandervines Fixed this and merged to master.
